#!/usr/bin/env python3
"""
Simple test to verify Gemini returns non-empty responses for AI suggestions
"""
import sys
import os

# Add server app to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '../../'))

from app.llm_service import LLMService

def test_gemini_response():
    """Test that Gemini returns a non-empty response"""
    print("🤖 Testing Gemini AI Response")
    print("=" * 40)
    
    try:
        # Test the exact call that AI suggestions make
        result = LLMService.generate_question(
            subject="python",
            context="beginner level. Question 1. Existing content: {}",
            question_type="open_ended",
            question_number=1
        )
        
        print(f"LLM Source: {result.get('llm_source', 'unknown')}")
        print(f"Generated by: {result.get('generated_by', 'unknown')}")
        
        # Check if we have question_text
        question_text = result.get('question_text', '')
        
        print(f"Question text length: {len(question_text)}")
        print(f"Is empty: {question_text.strip() == ''}")
        
        if question_text and question_text.strip():
            print(f"✅ Gemini response: {question_text[:150]}...")
            print("✅ Test PASSED - Gemini returned non-empty response")
            return True
        else:
            print("❌ Test FAILED - Gemini returned empty response")
            print(f"Full result: {result}")
            return False
            
    except Exception as e:
        print(f"❌ Test FAILED with error: {e}")
        import traceback
        traceback.print_exc()
        return False

if __name__ == "__main__":
    success = test_gemini_response()
    assert success, "Gemini test failed"